import { QuestionConfig, egyptianGovernorates, timeSlots } from './types';

export const questions: QuestionConfig[] = [
  {
    id: 'q1',
    number: 1,
    text: 'ما هو الاسم التجاري الرسمي للمشروع؟',
    hint: 'اكتب الاسم بالعربية والإنجليزية إن أمكن.',
    type: 'text',
    answerKey: 'brandName',
    section: 'brand-identity',
    icon: 'sparkles',
  },
  {
    id: 'q2',
    number: 2,
    text: 'هل لديك شعار لفظي تسويقي (Slogan)؟',
    hint: 'اتركه فارغاً لاقتراحات المصمم لاحقاً.',
    type: 'text',
    answerKey: 'slogan',
    section: 'brand-identity',
    icon: 'feather',
  },
  {
    id: 'q3',
    number: 3,
    text: 'ما هو قطاع ومجال عمل مشروعك؟',
    hint: 'اختر المجال الأقرب لنشاطك التجاري.',
    type: 'single',
    answerKey: 'industry',
    section: 'industry',
    icon: 'building',
    options: [
      { label: 'عقارات، مقاولات، هندسة وديكور', weight: 3, value: 'real_estate' },
      { label: 'مطاعم، كافيهات، ضيافة', weight: 2, value: 'hospitality' },
      { label: 'موضة، أزياء، عطور', weight: 2, value: 'fashion' },
      { label: 'تقنية، برمجيات، رقميات', weight: 2, value: 'technology' },
      { label: 'عيادات، تجميل، رعاية صحية', weight: 2, value: 'medical' },
      { label: 'تجارة، متاجر، إلكترونية', weight: 1, value: 'ecommerce' },
      { label: 'تعليم، تدريب، أكاديميات', weight: 2, value: 'education' },
      { label: 'سفر، سياحة، فنادق', weight: 2, value: 'travel' },
      { label: 'إنتاج، إعلان، ستوديوهات', weight: 2, value: 'production' },
    ],
  },
  {
    id: 'q4',
    number: 4,
    text: 'ما حالة المشروع الحالية؟',
    hint: 'هل نبني من الصفر أم نطور هوية موجودة؟',
    type: 'single',
    answerKey: 'projectStage',
    section: 'project-stage',
    icon: 'rocket',
    options: [
      { label: 'مشروع ناشئ جديد (Startup)', weight: 2 },
      { label: 'إعادة بناء هوية موجودة (Rebranding)', weight: 4 },
      { label: 'براند ناجح يحتاج عناصر إضافية', weight: 2 },
      { label: 'فكرة قيد الدراسة', weight: 1 },
    ],
  },
  {
    id: 'q5',
    number: 5,
    text: 'ما الرؤية والرسالة والقيم الجوهرية؟',
    hint: 'ما الذي يجعلك فريداً؟',
    type: 'textarea',
    answerKey: 'vision',
    section: 'strategy',
    icon: 'eye',
  },
  {
    id: 'q6',
    number: 6,
    text: 'من هو الجمهور المستهدف؟',
    hint: 'يمكنك اختيار أكثر من فئة.',
    type: 'multi',
    answerKey: 'targetAudience',
    section: 'audience',
    icon: 'users',
    options: [
      { label: 'النخبة والVIP', weight: 4 },
      { label: 'رجال أعمال وشركات (B2B)', weight: 3 },
      { label: 'رجال وشباب محترفين', weight: 2 },
      { label: 'سيدات مهتمات بالجمال', weight: 2 },
      { label: 'الشباب (Gen-Z)', weight: 1 },
      { label: 'عائلات والمجتمع العام', weight: 1 },
    ],
  },
  {
    id: 'q6b',
    number: 7,
    text: 'ما الفئة العمرية المستهدفة؟',
    hint: 'اختار الفئات الأقرب لجمهورك.',
    type: 'multi',
    answerKey: 'audienceAge',
    section: 'audience',
    icon: 'users',
    options: [
      { label: 'أقل من 18', weight: 1 },
      { label: '18-24', weight: 1 },
      { label: '25-34', weight: 2 },
      { label: '35-44', weight: 2 },
      { label: '45-54', weight: 3 },
      { label: '55+', weight: 3 },
    ],
  },
  {
    id: 'q6c',
    number: 8,
    text: 'ما التوجه الجندري للجمهور؟',
    hint: 'حدد الجنس الأقرب.',
    type: 'single',
    answerKey: 'audienceGender',
    section: 'audience',
    icon: 'users',
    options: [
      { label: 'ذكور بشكل رئيسي', weight: 2 },
      { label: 'إناث بشكل رئيسي', weight: 2 },
      { label: 'مختلط متوازن', weight: 1 },
      { label: 'لا يهم (منتج محايد)', weight: 1 },
    ],
  },
  {
    id: 'q6d',
    number: 9,
    text: 'ما المستوى الاقتصادي لجمهورك؟',
    hint: 'هذا يحدد عمق التعقيد البصري.',
    type: 'single',
    answerKey: 'audienceEconomic',
    section: 'audience',
    icon: 'users',
    options: [
      { label: 'A+ نخبة فائقة الثراء', weight: 4 },
      { label: 'A طبقة عليا', weight: 3 },
      { label: 'B طبقة متوسطة-عليا', weight: 2 },
      { label: 'C طبقة متوسطة', weight: 1 },
      { label: 'D+E اقتصادي', weight: 1 },
    ],
  },
  {
    id: 'q7',
    number: 10,
    text: 'ما النطاق الجغرافي لجمهورك؟',
    hint: 'هذا يحدد عملة التسعير.',
    type: 'single',
    answerKey: 'geography',
    section: 'geography',
    icon: 'globe',
    options: [
      { label: 'عالمي (أوروبا، أمريكا، آسيا)', weight: 5 },
      { label: 'إقليمي (الخليج، العرب)', weight: 3 },
      { label: 'محلي (مصر)', weight: 1 },
    ],
  },
  {
    id: 'q7b',
    number: 11,
    text: 'حدد المحافظة المستهدفة',
    hint: 'للمشروعات المحلية المصرية.',
    type: 'governorate',
    answerKey: 'governorate',
    section: 'geography',
    icon: 'map-pin',
    conditionalShow: (a) => a.geography?.includes('محلي') || false,
  },
  {
    id: 'q7c',
    number: 12,
    text: 'ما حجم مشروعك التجاري؟',
    hint: 'يؤثر على نطاق الهوية وعدد التطبيقات.',
    type: 'single',
    answerKey: 'businessSize',
    section: 'geography',
    icon: 'building',
    options: [
      { label: 'مشروع فردي أو مايكرو', weight: 1 },
      { label: 'شركة صغيرة (1-10 موظف)', weight: 2 },
      { label: 'شركة متوسطة (10-50 موظف)', weight: 3 },
      { label: 'مؤسسة كبيرة (50+ موظف)', weight: 4 },
      { label: 'شركة مساهمة أو مجموعة', weight: 5 },
    ],
  },
  {
    id: 'q8',
    number: 13,
    text: 'ما فئة تسعير منتجاتك في السوق؟',
    hint: 'هذا يحدد عمق التعقيد البصري المطلوب.',
    type: 'single',
    answerKey: 'pricePosition',
    section: 'positioning',
    icon: 'crown',
    options: [
      { label: 'لاكشري حصري (Luxury)', weight: 4 },
      { label: 'بريميوم راقي (Premium)', weight: 3 },
      { label: 'متوسط ومتوازن', weight: 2 },
      { label: 'اقتصادي', weight: 1 },
    ],
  },
  {
    id: 'q9',
    number: 14,
    text: 'من هم أبرز المنافسين؟',
    hint: 'اذكر 2-3 منافسين لتصميم متميز.',
    type: 'textarea',
    answerKey: 'competitors',
    section: 'competition',
    icon: 'swords',
  },
  {
    id: 'q10',
    number: 15,
    text: 'ما شخصية البراند؟',
    hint: 'اختر 2-4 صفات.',
    type: 'multi',
    answerKey: 'brandPersonality',
    section: 'personality',
    icon: 'heart',
    options: [
      { label: 'ملكي وفاخر', weight: 4 },
      { label: 'رسمي ومحترف', weight: 3 },
      { label: 'جريء ومبدع', weight: 2 },
      { label: 'مينيمال وهادئ', weight: 2 },
      { label: 'تقني ودقيق', weight: 2 },
      { label: 'دافئ وإنساني', weight: 1 },
    ],
  },
  {
    id: 'q10b',
    number: 16,
    text: 'ما أصل (Archetype) البراند؟',
    hint: 'اختار القريب لروح البراند.',
    type: 'single',
    answerKey: 'brandArchetype',
    section: 'personality',
    icon: 'sparkles',
    options: [
      { label: 'الحاكم (Ruler) — سلطة وسيطرة', weight: 4 },
      { label: 'المبدع (Creator) — ابتكار وتفرد', weight: 3 },
      { label: 'البطل (Hero) — إنجاز وتفوق', weight: 3 },
      { label: 'الحكيم (Sage) — معرفة وخبرة', weight: 2 },
      { label: 'المستكشف (Explorer) — حرية ومغامرة', weight: 2 },
      { label: 'العاشق (Lover) — عاطفة وجمال', weight: 2 },
      { label: 'المرح (Jester) — مرح وترفيه', weight: 1 },
      { label: 'الراعي (Caregiver) — رعاية وأمان', weight: 1 },
    ],
  },
  {
    id: 'q11',
    number: 17,
    text: 'ما التوجه الفني المفضل للشعار؟',
    hint: 'اختر القريب لرؤيتك.',
    type: 'single',
    answerKey: 'logoDirection',
    section: 'visual',
    icon: 'pen-tool',
    options: [
      { label: 'مونوغرام (Monogram)', weight: 3 },
      { label: 'خطي مخصص (Typography)', weight: 3 },
      { label: 'أيقوني رمزي (Symbolic)', weight: 2 },
      { label: 'مينيماليست', weight: 2 },
      { label: 'ختم رسمي (Emblem)', weight: 2 },
    ],
  },
  {
    id: 'q12',
    number: 18,
    text: 'ما اللوحة اللونية المفضلة؟',
    hint: 'اختر التوجه اللوني.',
    type: 'color',
    answerKey: 'preferredColors',
    section: 'visual',
    icon: 'palette',
  },
  {
    id: 'q13',
    number: 19,
    text: 'ما حجم المخرجات المطلوب؟',
    hint: 'يحدد الباقة والتسعير.',
    type: 'single',
    answerKey: 'deliverableScope',
    section: 'scope',
    icon: 'package',
    options: [
      { label: 'الهوية الكاملة (شعار + دليل + قرطاسية + تغليف)', weight: 4, tier: 'PREMIUM' },
      { label: 'المتوسطة (شعار + مطبوعات + سوشيال)', weight: 3, tier: 'MEDIUM' },
      { label: 'الاقتصادية (هوية سريعة)', weight: 2, tier: 'BUDGET' },
      { label: 'ميكرو (شعار فقط)', weight: 1, tier: 'MICRO' },
    ],
  },
  {
    id: 'q14',
    number: 20,
    text: 'هل سبق لك تصميم هوية من قبل؟',
    hint: 'يساعدنا في فهم توقعاتك.',
    type: 'single',
    answerKey: 'previousExperience',
    section: 'history',
    icon: 'history',
    options: [
      { label: 'نعم، لم تكن بالمستوى المطلوب', weight: 3 },
      { label: 'نعم، جيدة لكن أريد تحديث', weight: 2 },
      { label: 'لا، هذه أول مرة', weight: 1 },
    ],
  },
  {
    id: 'q14b',
    number: 21,
    text: 'ما تقييمك لتجربتك البصرية السابقة؟',
    hint: 'حدد مستوى الوعي البصري.',
    type: 'single',
    answerKey: 'visualHistory',
    section: 'history',
    icon: 'eye',
    options: [
      { label: 'لدي هوية متكاملة وأريد تطويرها', weight: 4 },
      { label: 'لدي عناصر بسيطة غير مكتملة', weight: 2 },
      { label: 'لدي محاولات سابقة غير ناجحة', weight: 3 },
      { label: 'أبدأ من الصفر تماماً', weight: 1 },
    ],
  },
  {
    id: 'q15',
    number: 22,
    text: 'أين ستطبق الهوية؟',
    hint: 'يمكنك اختيار أكثر من قناة.',
    type: 'multi',
    answerKey: 'applicationChannels',
    section: 'application',
    icon: 'layout',
    options: [
      { label: 'رقمياً (سوشيال، مواقع)', weight: 2 },
      { label: 'تغليف ومنتجات', weight: 3 },
      { label: 'مطبوعات وقرطاسية', weight: 2 },
      { label: 'لوحات ويونيفورم', weight: 3 },
    ],
  },
  {
    id: 'q16',
    number: 23,
    text: 'ما نوعية الخطوط المفضلة؟',
    hint: 'الخطوط هي صوت البراند.',
    type: 'single',
    answerKey: 'typographyStyle',
    section: 'typography',
    icon: 'type',
    options: [
      { label: 'سيرف كلاسيكي (Serif)', weight: 3 },
      { label: 'سان سيرف حديث (Sans-Serif)', weight: 2 },
      { label: 'كاليجرافي عربي', weight: 3 },
    ],
  },
  {
    id: 'q16b',
    number: 24,
    text: 'ما مستوى التفصيل في الخطوط؟',
    hint: 'الخطوط المخصصة تزيد الجودة والتكلفة.',
    type: 'single',
    answerKey: 'typographyDetail',
    section: 'typography',
    icon: 'type',
    options: [
      { label: 'خطوط جاهزة مختارة بعناية', weight: 1 },
      { label: 'تعديل جزئي على خطوط موجودة', weight: 2 },
      { label: 'تصميم خط مخصص بالكامل (Custom Type)', weight: 4 },
      { label: 'كاليجرافي عربي مخصص مرسوم يدوياً', weight: 4 },
    ],
  },
  {
    id: 'q17',
    number: 25,
    text: 'كيف تنظر للاستثمار في الهوية؟',
    hint: 'فهم فلسفتك الاستثمارية.',
    type: 'single',
    answerKey: 'investmentPhilosophy',
    section: 'investment',
    icon: 'trending-up',
    options: [
      { label: 'أصل استثماري أساسي', weight: 4 },
      { label: 'توازن بين الجودة والسعر', weight: 2 },
      { label: 'حلول اقتصادية للاختبار', weight: 1 },
    ],
  },
  {
    id: 'q17b',
    number: 26,
    text: 'ما ميزانيتك المتاحة؟',
    hint: 'حدد النطاق أو اتركه مفتوحاً.',
    type: 'budget',
    answerKey: 'budgetRange',
    section: 'investment',
    icon: 'wallet',
    options: [
      { label: 'اقتصادية (أقل من 3,000 ج.م)', weight: 1, value: 'economical' },
      { label: 'متوسطة (3,000 - 7,000 ج.م)', weight: 2, value: 'medium' },
      { label: 'جيدة (7,000 - 12,000 ج.م)', weight: 3, value: 'good' },
      { label: 'بريميوم (أكثر من 12,000 ج.م)', weight: 4, value: 'premium' },
      { label: 'مفتوحة — حدد الأنسب لمشروعي', weight: 3, value: 'open' },
    ],
  },
  {
    id: 'q18',
    number: 27,
    text: 'هل لديك مراجع بصرية ملهمة؟',
    hint: 'ملفات أو روابط من Behance/Pinterest.',
    type: 'file',
    answerKey: 'referenceFiles',
    section: 'references',
    icon: 'image',
  },
  {
    id: 'q19',
    number: 28,
    text: 'ما الإطار الزمني المفضل؟',
    hint: 'الوقت الأقصر يزيد التكلفة. الوقت المرن يضمن أعلى جودة.',
    type: 'slider',
    answerKey: 'timelineDays',
    section: 'timeline',
    icon: 'clock',
  },
  {
    id: 'q19b',
    number: 29,
    text: 'ما فترة التواصل المناسبة؟',
    hint: 'للتنسيق ومتابعة سير العمل.',
    type: 'timeline-slot',
    answerKey: 'timelineSlot',
    section: 'timeline',
    icon: 'clock',
  },
  {
    id: 'q20',
    number: 30,
    text: 'خدمات إضافية قد تفيد مشروعك؟',
    hint: 'اختر ما يناسبك — أو تخطى.',
    type: 'multi',
    answerKey: 'additionalServices',
    section: 'extras',
    icon: 'plus',
    options: [
      { label: 'موشن الشعار (Logo Animation)', weight: 3 },
      { label: 'دليل البراند (Brand Book)', weight: 3 },
      { label: 'قوالب سوشيال ميديا', weight: 2 },
      { label: 'تصميم تغليف منتجات', weight: 3 },
      { label: 'لا أحتاج أي شيء إضافي', weight: 0 },
    ],
  },
  {
    id: 'q21',
    number: 31,
    text: 'ملاحظات أو شروط ختامية؟',
    hint: 'أي تفاصيل إضافية.',
    type: 'textarea',
    answerKey: 'additionalNotes',
    section: 'closing',
    icon: 'message',
  },
];

export const colorPalettes = [
  {
    name: 'الفخامة المفرطة الداكنة',
    fullName: 'الفخامة المفرطة الداكنة',
    gradient: 'linear-gradient(135deg, #0A0A0A, #1C1C1E)',
    category: 'dark-luxury',
  },
  {
    name: 'التوجه الملكي',
    fullName: 'التوجه الملكي (ذهبي/بيج)',
    gradient: 'linear-gradient(135deg, #C9A84C, #FAF6EC)',
    category: 'royal',
  },
  {
    name: 'الثقة والاستقرار',
    fullName: 'الثقة والاستقرار (كحلي/سماوي)',
    gradient: 'linear-gradient(135deg, #0A2540, #639FAB)',
    category: 'trust',
  },
  {
    name: 'النقاء والاستدامة',
    fullName: 'النقاء والاستدامة (أخضر)',
    gradient: 'linear-gradient(135deg, #134021, #A3E2C9)',
    category: 'organic',
  },
  {
    name: 'الطاقة والجرأة',
    fullName: 'الطاقة والجرأة (أحمر/برتقالي)',
    gradient: 'linear-gradient(135deg, #A61C1C, #FF4D4D)',
    category: 'energy',
  },
  {
    name: 'الأصالة والعمق',
    fullName: 'الأصالة والعمق (ترابي/بني)',
    gradient: 'linear-gradient(135deg, #4A3728, #D2B48C)',
    category: 'earthy',
  },
];

export { egyptianGovernorates, timeSlots };
